CREATE TABLE lbcat.table_datetime (id INT AUTO_INCREMENT NOT NULL, p0 datetime(0) DEFAULT NOW() NOT NULL, p6 datetime(6) DEFAULT NOW(6) NOT NULL, CONSTRAINT PK_TABLE_DATETIME PRIMARY KEY (id))

CREATE TABLE lbcat.table_timestamp (id INT AUTO_INCREMENT NOT NULL, p0 TIMESTAMP(0) DEFAULT NOW() NOT NULL, p6 TIMESTAMP(6) DEFAULT NOW(6) NOT NULL, CONSTRAINT PK_TABLE_TIMESTAMP PRIMARY KEY (id))