name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    uses: liquibase/build-logic/.github/workflows/create-release.yml@afaacfdeb9cc754b4c3fc91a718be7283491b879 # v0.7.8
    secrets: inherit
